version: '3.7'
services:
  mqtt:
    image: eclipse-mosquitto:2.0.14
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./password.tx:/mosquitto/config/password.txt"